{
 "title": "ClickPulse Analytics Dashboard",
 "time": { "from": "2010-12-01T07:25:42.407Z", "to": "2011-01-08T22:40:07.697Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Reginal Sales", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sales Breakdown by Country Over Time",
   "type": "piechart",
   "description": "This multi-dimensional query highlights how ClickHouse can handle complex grouping. You can use a stacked bar chart or a heatmap to visualize the sales trends per country over the months.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  Country, \r\n  toStartOfMonth(InvoiceDate) AS month, \r\n  sum(Quantity * UnitPrice) AS total_sales\r\nFROM online_retail\r\nGROUP BY Country, month\r\nORDER BY Country, month;"
    }
   ]
  },
  {
   "title": "Sales by Country",
   "type": "table",
   "description": "Shows the breakdown of total sales by country.",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  Country, \r\n  sum(Quantity * UnitPrice) AS total_sales\r\nFROM online_retail\r\nGROUP BY Country\r\nORDER BY total_sales DESC;"
    }
   ]
  },
  { "title": "Top Products", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Top 10 Products by Sales",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  StockCode, \r\n  sum(Quantity * UnitPrice) AS total_sales\r\nFROM online_retail\r\nGROUP BY StockCode\r\nORDER BY total_sales DESC\r\nLIMIT 10;"
    }
   ]
  },
  { "title": "Trend Value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Monthly Sales Trend",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  toStartOfMonth(InvoiceDate) AS month, \r\n  sum(Quantity * UnitPrice) AS total_sales\r\nFROM online_retail\r\nGROUP BY month\r\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Average Order Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(order_total) AS avg_order_value FROM (\r\n  SELECT InvoiceNo, sum(Quantity * UnitPrice) AS order_total\r\n  FROM online_retail\r\n  GROUP BY InvoiceNo\r\n)"
    }
   ]
  },
  { "title": "Sales per Day", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Sales per Day",
   "type": "timeseries",
   "description": "Displays the daily aggregated sales.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  toDate(InvoiceDate) AS sale_date, \r\n  sum(Quantity * UnitPrice) AS total_sales\r\nFROM online_retail\r\nGROUP BY sale_date\r\nORDER BY sale_date;"
    }
   ]
  },
  { "title": "Sales Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Daily Order Count and Average Order Value",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  toDate(InvoiceDate) AS sale_date, \r\n  countDistinct(InvoiceNo) AS order_count,\r\n  avg(order_total) AS avg_order_value\r\nFROM (\r\n  SELECT \r\n    InvoiceNo, \r\n    InvoiceDate,\r\n    sum(Quantity * UnitPrice) AS order_total\r\n  FROM online_retail\r\n  GROUP BY InvoiceNo, InvoiceDate\r\n)\r\nGROUP BY sale_date\r\nORDER BY sale_date;"
    }
   ]
  }
 ]
}