name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        env: # Production environment variables from GitHub Secrets
          GRAFANA_PORT: ${{ secrets.GRAFANA_PORT }}
          GF_SERVER_ROOT_URL: ${{ secrets.GF_SERVER_ROOT_URL }}
          GF_SERVER_SERVE_FROM_SUB_PATH: ${{ secrets.GF_SERVER_SERVE_FROM_SUB_PATH }}
          GF_SERVER_DOMAIN: ${{ secrets.GF_SERVER_DOMAIN }}
          GF_SERVER_PROTOCOL: ${{ secrets.GF_SERVER_PROTOCOL }}
          GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "false"
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /srv/clickpulse
            git config --global --add safe.directory /srv/clickpulse # Ensure Git considers this directory safe
            git pull origin main
            git clean -fd
            docker compose down
            docker compose up --build -d